/*
 * This file is generated by jOOQ.
*/
package qooj.jooq.generate;


import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import qooj.jooq.generate.tables.Test1;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Qooj extends SchemaImpl {

    private static final long serialVersionUID = 2000263966;

    /**
     * The reference instance of <code>qooj</code>
     */
    public static final Qooj QOOJ = new Qooj();

    /**
     * The table <code>qooj.test1</code>.
     */
    public final Test1 TEST1 = qooj.jooq.generate.tables.Test1.TEST1;

    /**
     * No further instances allowed
     */
    private Qooj() {
        super("qooj", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Test1.TEST1);
    }
}
