/*
 * This file is generated by jOOQ.
*/
package qooj.jooq.generate;


import javax.annotation.Generated;

import qooj.jooq.generate.tables.Test1;


/**
 * Convenience access to all tables in qooj
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>qooj.test1</code>.
     */
    public static final Test1 TEST1 = qooj.jooq.generate.tables.Test1.TEST1;
}
