/*
 * This file is generated by jOOQ.
*/
package qooj.jooq.generate.tables.records;


import java.math.BigDecimal;
import java.sql.Date;
import java.sql.Time;
import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.TableRecordImpl;

import qooj.jooq.generate.tables.Test1;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Test1Record extends TableRecordImpl<Test1Record> implements Record5<BigDecimal, String, Date, Timestamp, Time> {

    private static final long serialVersionUID = -1608607282;

    /**
     * Setter for <code>qooj.test1.code</code>.
     */
    public void setCode(BigDecimal value) {
        set(0, value);
    }

    /**
     * Getter for <code>qooj.test1.code</code>.
     */
    public BigDecimal getCode() {
        return (BigDecimal) get(0);
    }

    /**
     * Setter for <code>qooj.test1.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>qooj.test1.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>qooj.test1.date1</code>.
     */
    public void setDate1(Date value) {
        set(2, value);
    }

    /**
     * Getter for <code>qooj.test1.date1</code>.
     */
    public Date getDate1() {
        return (Date) get(2);
    }

    /**
     * Setter for <code>qooj.test1.date2</code>.
     */
    public void setDate2(Timestamp value) {
        set(3, value);
    }

    /**
     * Getter for <code>qooj.test1.date2</code>.
     */
    public Timestamp getDate2() {
        return (Timestamp) get(3);
    }

    /**
     * Setter for <code>qooj.test1.time1</code>.
     */
    public void setTime1(Time value) {
        set(4, value);
    }

    /**
     * Getter for <code>qooj.test1.time1</code>.
     */
    public Time getTime1() {
        return (Time) get(4);
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<BigDecimal, String, Date, Timestamp, Time> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<BigDecimal, String, Date, Timestamp, Time> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field1() {
        return Test1.TEST1.CODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Test1.TEST1.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Date> field3() {
        return Test1.TEST1.DATE1;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field4() {
        return Test1.TEST1.DATE2;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Time> field5() {
        return Test1.TEST1.TIME1;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value1() {
        return getCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date value3() {
        return getDate1();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value4() {
        return getDate2();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Time value5() {
        return getTime1();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Test1Record value1(BigDecimal value) {
        setCode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Test1Record value2(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Test1Record value3(Date value) {
        setDate1(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Test1Record value4(Timestamp value) {
        setDate2(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Test1Record value5(Time value) {
        setTime1(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Test1Record values(BigDecimal value1, String value2, Date value3, Timestamp value4, Time value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached Test1Record
     */
    public Test1Record() {
        super(Test1.TEST1);
    }

    /**
     * Create a detached, initialised Test1Record
     */
    public Test1Record(BigDecimal code, String name, Date date1, Timestamp date2, Time time1) {
        super(Test1.TEST1);

        set(0, code);
        set(1, name);
        set(2, date1);
        set(3, date2);
        set(4, time1);
    }
}
